package com.denuncia.persistencia.dominio;
// Generated 24/08/2014 12:41:26 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Bitacora generated by hbm2java
 */
public class Bitacora  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idBitacora;
     private String peticion;
     private String respuesta;
     private Date fechaHoraPeticion;
     private Date fechaHoraRespuesta;

    public Bitacora() {
    }

	
    public Bitacora(String peticion, Date fechaHoraPeticion, Date fechaHoraRespuesta) {
        this.peticion = peticion;
        this.fechaHoraPeticion = fechaHoraPeticion;
        this.fechaHoraRespuesta = fechaHoraRespuesta;
    }
    public Bitacora(String peticion, String respuesta, Date fechaHoraPeticion, Date fechaHoraRespuesta) {
       this.peticion = peticion;
       this.respuesta = respuesta;
       this.fechaHoraPeticion = fechaHoraPeticion;
       this.fechaHoraRespuesta = fechaHoraRespuesta;
    }
   
    public Integer getIdBitacora() {
        return this.idBitacora;
    }
    
    public void setIdBitacora(Integer idBitacora) {
        this.idBitacora = idBitacora;
    }
    public String getPeticion() {
        return this.peticion;
    }
    
    public void setPeticion(String peticion) {
        this.peticion = peticion;
    }
    public String getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }
    public Date getFechaHoraPeticion() {
        return this.fechaHoraPeticion;
    }
    
    public void setFechaHoraPeticion(Date fechaHoraPeticion) {
        this.fechaHoraPeticion = fechaHoraPeticion;
    }
    public Date getFechaHoraRespuesta() {
        return this.fechaHoraRespuesta;
    }
    
    public void setFechaHoraRespuesta(Date fechaHoraRespuesta) {
        this.fechaHoraRespuesta = fechaHoraRespuesta;
    }




}


