package com.denuncia.persistencia.dominio;
// Generated 24/08/2014 12:41:26 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * CatDelegacion generated by hbm2java
 */
public class CatDelegacion  implements java.io.Serializable {


     private Integer idDelegacion;
     private String nombre;
     private Set instConDels = new HashSet(0);

    public CatDelegacion() {
    }

	
    public CatDelegacion(String nombre) {
        this.nombre = nombre;
    }
    public CatDelegacion(String nombre, Set instConDels) {
       this.nombre = nombre;
       this.instConDels = instConDels;
    }
   
    public Integer getIdDelegacion() {
        return this.idDelegacion;
    }
    
    public void setIdDelegacion(Integer idDelegacion) {
        this.idDelegacion = idDelegacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getInstConDels() {
        return this.instConDels;
    }
    
    public void setInstConDels(Set instConDels) {
        this.instConDels = instConDels;
    }




}


