package com.denuncia.persistencia.dominio;
// Generated 24/08/2014 12:41:26 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Denuncia generated by hbm2java
 */
public class Denuncia  implements java.io.Serializable {


     private Integer idDenuncia;
     private CatCategoriaDenuncia catCategoriaDenuncia;
     private String direccion;
     private String emailUsuario;
     private Integer contador;
     private BigDecimal latitud;
     private BigDecimal longitud;
     private Date fechaHoraDenuncia;
     private Date fechaHoraActCont;
     private Set emailDenuncias = new HashSet(0);

    public Denuncia() {
    }

	
    public Denuncia(CatCategoriaDenuncia catCategoriaDenuncia, Date fechaHoraDenuncia, Date fechaHoraActCont) {
        this.catCategoriaDenuncia = catCategoriaDenuncia;
        this.fechaHoraDenuncia = fechaHoraDenuncia;
        this.fechaHoraActCont = fechaHoraActCont;
    }
    public Denuncia(CatCategoriaDenuncia catCategoriaDenuncia, String direccion, String emailUsuario, Integer contador, BigDecimal latitud, BigDecimal longitud, Date fechaHoraDenuncia, Date fechaHoraActCont, Set emailDenuncias) {
       this.catCategoriaDenuncia = catCategoriaDenuncia;
       this.direccion = direccion;
       this.emailUsuario = emailUsuario;
       this.contador = contador;
       this.latitud = latitud;
       this.longitud = longitud;
       this.fechaHoraDenuncia = fechaHoraDenuncia;
       this.fechaHoraActCont = fechaHoraActCont;
       this.emailDenuncias = emailDenuncias;
    }
   
    public Integer getIdDenuncia() {
        return this.idDenuncia;
    }
    
    public void setIdDenuncia(Integer idDenuncia) {
        this.idDenuncia = idDenuncia;
    }
    public CatCategoriaDenuncia getCatCategoriaDenuncia() {
        return this.catCategoriaDenuncia;
    }
    
    public void setCatCategoriaDenuncia(CatCategoriaDenuncia catCategoriaDenuncia) {
        this.catCategoriaDenuncia = catCategoriaDenuncia;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getEmailUsuario() {
        return this.emailUsuario;
    }
    
    public void setEmailUsuario(String emailUsuario) {
        this.emailUsuario = emailUsuario;
    }
    public Integer getContador() {
        return this.contador;
    }
    
    public void setContador(Integer contador) {
        this.contador = contador;
    }
    public BigDecimal getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(BigDecimal latitud) {
        this.latitud = latitud;
    }
    public BigDecimal getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(BigDecimal longitud) {
        this.longitud = longitud;
    }
    public Date getFechaHoraDenuncia() {
        return this.fechaHoraDenuncia;
    }
    
    public void setFechaHoraDenuncia(Date fechaHoraDenuncia) {
        this.fechaHoraDenuncia = fechaHoraDenuncia;
    }
    public Date getFechaHoraActCont() {
        return this.fechaHoraActCont;
    }
    
    public void setFechaHoraActCont(Date fechaHoraActCont) {
        this.fechaHoraActCont = fechaHoraActCont;
    }
    public Set getEmailDenuncias() {
        return this.emailDenuncias;
    }
    
    public void setEmailDenuncias(Set emailDenuncias) {
        this.emailDenuncias = emailDenuncias;
    }




}


