package com.denuncia.persistencia.dominio;
// Generated 24/08/2014 12:41:26 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * CatContacto generated by hbm2java
 */
public class CatContacto  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idContacto;
     private String nombre;
     private String email;
     private Set instConDels = new HashSet(0);
     private Set emailDenuncias = new HashSet(0);

    public CatContacto() {
    }

	
    public CatContacto(String nombre, String email) {
        this.nombre = nombre;
        this.email = email;
    }
    public CatContacto(String nombre, String email, Set instConDels, Set emailDenuncias) {
       this.nombre = nombre;
       this.email = email;
       this.instConDels = instConDels;
       this.emailDenuncias = emailDenuncias;
    }
   
    public Integer getIdContacto() {
        return this.idContacto;
    }
    
    public void setIdContacto(Integer idContacto) {
        this.idContacto = idContacto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getInstConDels() {
        return this.instConDels;
    }
    
    public void setInstConDels(Set instConDels) {
        this.instConDels = instConDels;
    }
    public Set getEmailDenuncias() {
        return this.emailDenuncias;
    }
    
    public void setEmailDenuncias(Set emailDenuncias) {
        this.emailDenuncias = emailDenuncias;
    }




}


