package com.denuncia.persistencia.dominio;
// Generated 24/08/2014 12:41:26 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * CatEstatusEmail generated by hbm2java
 */
public class CatEstatusEmail  implements java.io.Serializable {


     private Integer idEstatusEmail;
     private String descripcion;
     private Set emailDenuncias = new HashSet(0);

    public CatEstatusEmail() {
    }

	
    public CatEstatusEmail(String descripcion) {
        this.descripcion = descripcion;
    }
    public CatEstatusEmail(String descripcion, Set emailDenuncias) {
       this.descripcion = descripcion;
       this.emailDenuncias = emailDenuncias;
    }
   
    public Integer getIdEstatusEmail() {
        return this.idEstatusEmail;
    }
    
    public void setIdEstatusEmail(Integer idEstatusEmail) {
        this.idEstatusEmail = idEstatusEmail;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getEmailDenuncias() {
        return this.emailDenuncias;
    }
    
    public void setEmailDenuncias(Set emailDenuncias) {
        this.emailDenuncias = emailDenuncias;
    }




}


