package com.denuncia.persistencia.dominio;
// Generated 24/08/2014 12:41:26 AM by Hibernate Tools 3.6.0



/**
 * Configuracion generated by hbm2java
 */
public class Configuracion  implements java.io.Serializable {


     private Integer idConfiguracion;
     private String descripcion;
     private String valor;

    public Configuracion() {
    }

    public Configuracion(String descripcion, String valor) {
       this.descripcion = descripcion;
       this.valor = valor;
    }
   
    public Integer getIdConfiguracion() {
        return this.idConfiguracion;
    }
    
    public void setIdConfiguracion(Integer idConfiguracion) {
        this.idConfiguracion = idConfiguracion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }




}


