package com.denuncia.persistencia.dominio;
// Generated 24/08/2014 12:41:26 AM by Hibernate Tools 3.6.0



/**
 * EmailDenuncia generated by hbm2java
 */
public class EmailDenuncia  implements java.io.Serializable {


     private Integer idEmailDenuncia;
     private CatContacto catContacto;
     private Denuncia denuncia;
     private CatEstatusEmail catEstatusEmail;

    public EmailDenuncia() {
    }

    public EmailDenuncia(CatContacto catContacto, Denuncia denuncia, CatEstatusEmail catEstatusEmail) {
       this.catContacto = catContacto;
       this.denuncia = denuncia;
       this.catEstatusEmail = catEstatusEmail;
    }
   
    public Integer getIdEmailDenuncia() {
        return this.idEmailDenuncia;
    }
    
    public void setIdEmailDenuncia(Integer idEmailDenuncia) {
        this.idEmailDenuncia = idEmailDenuncia;
    }
    public CatContacto getCatContacto() {
        return this.catContacto;
    }
    
    public void setCatContacto(CatContacto catContacto) {
        this.catContacto = catContacto;
    }
    public Denuncia getDenuncia() {
        return this.denuncia;
    }
    
    public void setDenuncia(Denuncia denuncia) {
        this.denuncia = denuncia;
    }
    public CatEstatusEmail getCatEstatusEmail() {
        return this.catEstatusEmail;
    }
    
    public void setCatEstatusEmail(CatEstatusEmail catEstatusEmail) {
        this.catEstatusEmail = catEstatusEmail;
    }




}


