package com.denuncia.ciudadana.dominio;

// default package
// Generated 26/08/2014 05:00:32 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bitacora generated by hbm2java
 */
@Entity
@Table(name = "bitacora", catalog = "denuncia")
public class Bitacora implements java.io.Serializable {

	private Integer idBitacora;
	private String peticion;
	private String respuesta;
	private Date fechaHoraPeticion;
	private Date fechaHoraRespuesta;

	public Bitacora() {
	}

	public Bitacora(String peticion, Date fechaHoraPeticion,
			Date fechaHoraRespuesta) {
		this.peticion = peticion;
		this.fechaHoraPeticion = fechaHoraPeticion;
		this.fechaHoraRespuesta = fechaHoraRespuesta;
	}

	public Bitacora(String peticion, String respuesta, Date fechaHoraPeticion,
			Date fechaHoraRespuesta) {
		this.peticion = peticion;
		this.respuesta = respuesta;
		this.fechaHoraPeticion = fechaHoraPeticion;
		this.fechaHoraRespuesta = fechaHoraRespuesta;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id_Bitacora", unique = true, nullable = false)
	public Integer getIdBitacora() {
		return this.idBitacora;
	}

	public void setIdBitacora(Integer idBitacora) {
		this.idBitacora = idBitacora;
	}

	@Column(name = "Peticion", nullable = false)
	public String getPeticion() {
		return this.peticion;
	}

	public void setPeticion(String peticion) {
		this.peticion = peticion;
	}

	@Column(name = "Respuesta")
	public String getRespuesta() {
		return this.respuesta;
	}

	public void setRespuesta(String respuesta) {
		this.respuesta = respuesta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Hora_Peticion", nullable = false, length = 19)
	public Date getFechaHoraPeticion() {
		return this.fechaHoraPeticion;
	}

	public void setFechaHoraPeticion(Date fechaHoraPeticion) {
		this.fechaHoraPeticion = fechaHoraPeticion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Hora_Respuesta", nullable = false, length = 19)
	public Date getFechaHoraRespuesta() {
		return this.fechaHoraRespuesta;
	}

	public void setFechaHoraRespuesta(Date fechaHoraRespuesta) {
		this.fechaHoraRespuesta = fechaHoraRespuesta;
	}

}
