package com.denuncia.ciudadana.dominio;

/// default package
// Generated 26/08/2014 05:00:32 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatContacto generated by hbm2java
 */
@Entity
@Table(name = "cat_contacto", catalog = "denuncia")
public class CatContacto implements java.io.Serializable {

	private Integer idContacto;
	private String nombre;
	private String email;
	private Set<InstConDel> instConDels = new HashSet<InstConDel>(0);
	private Set<EmailDenuncia> emailDenuncias = new HashSet<EmailDenuncia>(0);

	public CatContacto() {
	}

	public CatContacto(String nombre, String email) {
		this.nombre = nombre;
		this.email = email;
	}

	public CatContacto(String nombre, String email,
			Set<InstConDel> instConDels, Set<EmailDenuncia> emailDenuncias) {
		this.nombre = nombre;
		this.email = email;
		this.instConDels = instConDels;
		this.emailDenuncias = emailDenuncias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id_Contacto", unique = true, nullable = false)
	public Integer getIdContacto() {
		return this.idContacto;
	}

	public void setIdContacto(Integer idContacto) {
		this.idContacto = idContacto;
	}

	@Column(name = "Nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catContacto")
	public Set<InstConDel> getInstConDels() {
		return this.instConDels;
	}

	public void setInstConDels(Set<InstConDel> instConDels) {
		this.instConDels = instConDels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catContacto")
	public Set<EmailDenuncia> getEmailDenuncias() {
		return this.emailDenuncias;
	}

	public void setEmailDenuncias(Set<EmailDenuncia> emailDenuncias) {
		this.emailDenuncias = emailDenuncias;
	}

}
