package com.denuncia.ciudadana.dominio;

/// default package
// Generated 26/08/2014 05:00:32 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatEstatusEmail generated by hbm2java
 */
@Entity
@Table(name = "cat_estatus_email", catalog = "denuncia")
public class CatEstatusEmail implements java.io.Serializable {

	private Integer idEstatusEmail;
	private String descripcion;
	private Set<EmailDenuncia> emailDenuncias = new HashSet<EmailDenuncia>(0);

	public CatEstatusEmail() {
	}

	public CatEstatusEmail(String descripcion) {
		this.descripcion = descripcion;
	}

	public CatEstatusEmail(String descripcion, Set<EmailDenuncia> emailDenuncias) {
		this.descripcion = descripcion;
		this.emailDenuncias = emailDenuncias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id_Estatus_Email", unique = true, nullable = false)
	public Integer getIdEstatusEmail() {
		return this.idEstatusEmail;
	}

	public void setIdEstatusEmail(Integer idEstatusEmail) {
		this.idEstatusEmail = idEstatusEmail;
	}

	@Column(name = "Descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catEstatusEmail")
	public Set<EmailDenuncia> getEmailDenuncias() {
		return this.emailDenuncias;
	}

	public void setEmailDenuncias(Set<EmailDenuncia> emailDenuncias) {
		this.emailDenuncias = emailDenuncias;
	}

}
