package com.denuncia.ciudadana.dominio;

/// default package
// Generated 26/08/2014 05:00:32 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmailDenuncia generated by hbm2java
 */
@Entity
@Table(name = "email_denuncia", catalog = "denuncia")
public class EmailDenuncia implements java.io.Serializable {

	private Integer idEmailDenuncia;
	private CatContacto catContacto;
	private Denuncia denuncia;
	private CatEstatusEmail catEstatusEmail;

	public EmailDenuncia() {
	}

	public EmailDenuncia(CatContacto catContacto, Denuncia denuncia,
			CatEstatusEmail catEstatusEmail) {
		this.catContacto = catContacto;
		this.denuncia = denuncia;
		this.catEstatusEmail = catEstatusEmail;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id_Email_Denuncia", unique = true, nullable = false)
	public Integer getIdEmailDenuncia() {
		return this.idEmailDenuncia;
	}

	public void setIdEmailDenuncia(Integer idEmailDenuncia) {
		this.idEmailDenuncia = idEmailDenuncia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_Contacto", nullable = false)
	public CatContacto getCatContacto() {
		return this.catContacto;
	}

	public void setCatContacto(CatContacto catContacto) {
		this.catContacto = catContacto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_Denuncia", nullable = false)
	public Denuncia getDenuncia() {
		return this.denuncia;
	}

	public void setDenuncia(Denuncia denuncia) {
		this.denuncia = denuncia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Estatus_Email", nullable = false)
	public CatEstatusEmail getCatEstatusEmail() {
		return this.catEstatusEmail;
	}

	public void setCatEstatusEmail(CatEstatusEmail catEstatusEmail) {
		this.catEstatusEmail = catEstatusEmail;
	}

}
