package com.denuncia.persistencia.dominio;
// Generated 24/08/2014 12:41:26 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * CatInstitucion generated by hbm2java
 */
public class CatInstitucion  implements java.io.Serializable {


     private Integer idInstitucion;
     private String nombre;
     private Set instConDels = new HashSet(0);

    public CatInstitucion() {
    }

	
    public CatInstitucion(String nombre) {
        this.nombre = nombre;
    }
    public CatInstitucion(String nombre, Set instConDels) {
       this.nombre = nombre;
       this.instConDels = instConDels;
    }
   
    public Integer getIdInstitucion() {
        return this.idInstitucion;
    }
    
    public void setIdInstitucion(Integer idInstitucion) {
        this.idInstitucion = idInstitucion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getInstConDels() {
        return this.instConDels;
    }
    
    public void setInstConDels(Set instConDels) {
        this.instConDels = instConDels;
    }




}


