package com.denuncia.ciudadana.dominio;

/// default package
// Generated 26/08/2014 05:00:32 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatCategoriaDenuncia generated by hbm2java
 */
@Entity
@Table(name = "cat_categoria_denuncia", catalog = "denuncia")
public class CatCategoriaDenuncia implements java.io.Serializable {

	private Integer idCatDenuncia;
	private String descripcion;
	private short envioEmail;
	private Set<InstConDel> instConDels = new HashSet<InstConDel>(0);
	private Set<Denuncia> denuncias = new HashSet<Denuncia>(0);

	public CatCategoriaDenuncia() {
	}

	public CatCategoriaDenuncia(String descripcion, short envioEmail) {
		this.descripcion = descripcion;
		this.envioEmail = envioEmail;
	}

	public CatCategoriaDenuncia(String descripcion, short envioEmail,
			Set<InstConDel> instConDels, Set<Denuncia> denuncias) {
		this.descripcion = descripcion;
		this.envioEmail = envioEmail;
		this.instConDels = instConDels;
		this.denuncias = denuncias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id_Cat_Denuncia", unique = true, nullable = false)
	public Integer getIdCatDenuncia() {
		return this.idCatDenuncia;
	}

	public void setIdCatDenuncia(Integer idCatDenuncia) {
		this.idCatDenuncia = idCatDenuncia;
	}

	@Column(name = "Descripcion", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "Envio_Email", nullable = false)
	public short getEnvioEmail() {
		return this.envioEmail;
	}

	public void setEnvioEmail(short envioEmail) {
		this.envioEmail = envioEmail;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catCategoriaDenuncia")
	public Set<InstConDel> getInstConDels() {
		return this.instConDels;
	}

	public void setInstConDels(Set<InstConDel> instConDels) {
		this.instConDels = instConDels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catCategoriaDenuncia")
	public Set<Denuncia> getDenuncias() {
		return this.denuncias;
	}

	public void setDenuncias(Set<Denuncia> denuncias) {
		this.denuncias = denuncias;
	}

}
