package com.denuncia.ciudadana.dominio;

/// default package
// Generated 26/08/2014 05:00:32 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatDelegacion generated by hbm2java
 */
@Entity
@Table(name = "cat_delegacion", catalog = "denuncia")
public class CatDelegacion implements java.io.Serializable {

	private Integer idDelegacion;
	private String nombre;
	private Set<InstConDel> instConDels = new HashSet<InstConDel>(0);

	public CatDelegacion() {
	}

	public CatDelegacion(String nombre) {
		this.nombre = nombre;
	}

	public CatDelegacion(String nombre, Set<InstConDel> instConDels) {
		this.nombre = nombre;
		this.instConDels = instConDels;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id_Delegacion", unique = true, nullable = false)
	public Integer getIdDelegacion() {
		return this.idDelegacion;
	}

	public void setIdDelegacion(Integer idDelegacion) {
		this.idDelegacion = idDelegacion;
	}

	@Column(name = "Nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catDelegacion")
	public Set<InstConDel> getInstConDels() {
		return this.instConDels;
	}

	public void setInstConDels(Set<InstConDel> instConDels) {
		this.instConDels = instConDels;
	}

}
