package com.denuncia.ciudadana.dominio;

/// default package
// Generated 26/08/2014 05:00:32 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Configuracion generated by hbm2java
 */
@Entity
@Table(name = "configuracion", catalog = "denuncia")
public class Configuracion implements java.io.Serializable {

	private Integer idConfiguracion;
	private String descripcion;
	private String valor;

	public Configuracion() {
	}

	public Configuracion(String descripcion, String valor) {
		this.descripcion = descripcion;
		this.valor = valor;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id_Configuracion", unique = true, nullable = false)
	public Integer getIdConfiguracion() {
		return this.idConfiguracion;
	}

	public void setIdConfiguracion(Integer idConfiguracion) {
		this.idConfiguracion = idConfiguracion;
	}

	@Column(name = "Descripcion", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "Valor", nullable = false, length = 50)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

}
