package com.denuncia.ciudadana.dominio;

/// default package
// Generated 26/08/2014 05:00:32 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Denuncia generated by hbm2java
 */
@Entity
@Table(name = "denuncia", catalog = "denuncia")
public class Denuncia implements java.io.Serializable {

	private Integer idDenuncia;
	private CatCategoriaDenuncia catCategoriaDenuncia;
	private String direccion;
	private String emailUsuario;
	private Integer contador;
	private BigDecimal latitud;
	private BigDecimal longitud;
	private Date fechaHoraDenuncia;
	private Date fechaHoraActCont;
	private Set<EmailDenuncia> emailDenuncias = new HashSet<EmailDenuncia>(0);
	private String imgPath;
	private String descripcion;

	public Denuncia() {
	}

	public Denuncia(CatCategoriaDenuncia catCategoriaDenuncia,
			Date fechaHoraDenuncia, Date fechaHoraActCont) {
		this.catCategoriaDenuncia = catCategoriaDenuncia;
		this.fechaHoraDenuncia = fechaHoraDenuncia;
		this.fechaHoraActCont = fechaHoraActCont;
	}

	public Denuncia(CatCategoriaDenuncia catCategoriaDenuncia,
			String direccion, String emailUsuario, Integer contador,
			BigDecimal latitud, BigDecimal longitud, Date fechaHoraDenuncia,
			Date fechaHoraActCont, Set<EmailDenuncia> emailDenuncias) {
		this.catCategoriaDenuncia = catCategoriaDenuncia;
		this.direccion = direccion;
		this.emailUsuario = emailUsuario;
		this.contador = contador;
		this.latitud = latitud;
		this.longitud = longitud;
		this.fechaHoraDenuncia = fechaHoraDenuncia;
		this.fechaHoraActCont = fechaHoraActCont;
		this.emailDenuncias = emailDenuncias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id_Denuncia", unique = true, nullable = false)
	public Integer getIdDenuncia() {
		return this.idDenuncia;
	}

	public void setIdDenuncia(Integer idDenuncia) {
		this.idDenuncia = idDenuncia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_Cat_Denuncia", nullable = false)
	public CatCategoriaDenuncia getCatCategoriaDenuncia() {
		return this.catCategoriaDenuncia;
	}

	public void setCatCategoriaDenuncia(
			CatCategoriaDenuncia catCategoriaDenuncia) {
		this.catCategoriaDenuncia = catCategoriaDenuncia;
	}

	@Column(name = "Direccion")
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "Email_Usuario", length = 50)
	public String getEmailUsuario() {
		return this.emailUsuario;
	}

	public void setEmailUsuario(String emailUsuario) {
		this.emailUsuario = emailUsuario;
	}

	@Column(name = "Contador")
	public Integer getContador() {
		return this.contador;
	}

	public void setContador(Integer contador) {
		this.contador = contador;
	}

	@Column(name = "Latitud", precision = 9, scale = 6)
	public BigDecimal getLatitud() {
		return this.latitud;
	}

	public void setLatitud(BigDecimal latitud) {
		this.latitud = latitud;
	}

	@Column(name = "Longitud", precision = 9, scale = 6)
	public BigDecimal getLongitud() {
		return this.longitud;
	}

	public void setLongitud(BigDecimal longitud) {
		this.longitud = longitud;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Hora_Denuncia", nullable = false, length = 19)
	public Date getFechaHoraDenuncia() {
		return this.fechaHoraDenuncia;
	}

	public void setFechaHoraDenuncia(Date fechaHoraDenuncia) {
		this.fechaHoraDenuncia = fechaHoraDenuncia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Hora_ActCont", nullable = false, length = 19)
	public Date getFechaHoraActCont() {
		return this.fechaHoraActCont;
	}

	public void setFechaHoraActCont(Date fechaHoraActCont) {
		this.fechaHoraActCont = fechaHoraActCont;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "denuncia")
	public Set<EmailDenuncia> getEmailDenuncias() {
		return this.emailDenuncias;
	}

	public void setEmailDenuncias(Set<EmailDenuncia> emailDenuncias) {
		this.emailDenuncias = emailDenuncias;
	}

	@Column(name = "Img_Path", length = 255)
	public String getImgPath() {
		return imgPath;
	}

	/**
	 * @param imgPath
	 *            the imgPath to set
	 */
	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	/**
	 * @return the descripcion
	 */
	@Column(name = "Descripcion", length = 55)
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * @param descripcion
	 *            the descripcion to set
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
