package com.denuncia.ciudadana.dominio;

/// default package
// Generated 26/08/2014 05:00:32 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InstConDel generated by hbm2java
 */
@Entity
@Table(name = "inst_con_del", catalog = "denuncia")
public class InstConDel implements java.io.Serializable {

	private Integer idInstConDel;
	private CatInstitucion catInstitucion;
	private CatDelegacion catDelegacion;
	private CatContacto catContacto;
	private CatCategoriaDenuncia catCategoriaDenuncia;

	public InstConDel() {
	}

	public InstConDel(CatInstitucion catInstitucion,
			CatDelegacion catDelegacion, CatContacto catContacto,
			CatCategoriaDenuncia catCategoriaDenuncia) {
		this.catInstitucion = catInstitucion;
		this.catDelegacion = catDelegacion;
		this.catContacto = catContacto;
		this.catCategoriaDenuncia = catCategoriaDenuncia;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id_Inst_Con_Del", unique = true, nullable = false)
	public Integer getIdInstConDel() {
		return this.idInstConDel;
	}

	public void setIdInstConDel(Integer idInstConDel) {
		this.idInstConDel = idInstConDel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_Institucion", nullable = false)
	public CatInstitucion getCatInstitucion() {
		return this.catInstitucion;
	}

	public void setCatInstitucion(CatInstitucion catInstitucion) {
		this.catInstitucion = catInstitucion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_Delegacion", nullable = false)
	public CatDelegacion getCatDelegacion() {
		return this.catDelegacion;
	}

	public void setCatDelegacion(CatDelegacion catDelegacion) {
		this.catDelegacion = catDelegacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_Contacto", nullable = false)
	public CatContacto getCatContacto() {
		return this.catContacto;
	}

	public void setCatContacto(CatContacto catContacto) {
		this.catContacto = catContacto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_Cat_Denuncia", nullable = false)
	public CatCategoriaDenuncia getCatCategoriaDenuncia() {
		return this.catCategoriaDenuncia;
	}

	public void setCatCategoriaDenuncia(
			CatCategoriaDenuncia catCategoriaDenuncia) {
		this.catCategoriaDenuncia = catCategoriaDenuncia;
	}

}
